import type { Product } from '@/types';

// ─── Static Product Data ───────────────────────────────────────────────────────
// All 8 products with local images and full specifications.
// This is the single source of truth — no WordPress dependency.

export const STATIC_PRODUCTS: Product[] = [
  {
    id: 1,
    slug: 'white-sewing-thread-paper-tube',
    title: 'White Sewing Thread Paper Tube',
    shortDescription:
      'Strong paper tubes specially made for sewing thread winding. Designed for smooth winding, good strength and reliable support.',
    description:
      '<p>Strong paper tubes specially made for sewing thread winding. Designed for smooth winding, good strength and reliable support.</p><p>Manufactured with precision to ensure consistent quality and reliable performance in textile and thread winding applications. Every tube is tested for strength and dimensional accuracy to meet the demands of high-speed thread winding machines.</p>',
    featuredImage: {
      id: 1,
      url: '/images/products/1 product.jpeg',
      alt: 'White Sewing Thread Paper Tube',
      width: 800,
      height: 600,
    },
    gallery: [],
    usedFor: ['Sewing Thread Winding'],
    applications: ['Textile Industry', 'Thread & Yarn Winding'],
    specifications: [
      { label: 'Thickness', value: '1.20 mm – 1.5 mm' },
      { label: 'Diameter', value: '9.5 mm' },
      { label: 'Length', value: '63 mm' },
      { label: 'Size', value: 'As per Requirement' },
      { label: 'Weight', value: '2.4 Gram' },
      { label: 'Usage / Application', value: 'Sewing Thread Winding' },
    ],
    seoTitle: 'White Sewing Thread Paper Tube | FAB Paper Tube',
    seoDescription:
      'Premium white sewing thread paper tubes. Thickness 1.20–1.5mm, Diameter 9.5mm, Length 63mm, Weight 2.4g. Manufactured by FAB Paper Tube, Gujarat.',
    acf: {},
    productOrder: 1,
    thickness: '1.20 mm – 1.5 mm',
    diameter: '9.5 mm',
    length: '63 mm',
    size: 'As per Requirement',
    weight: '2.4 Gram',
    usage: 'Sewing Thread Winding',
  },
  {
    id: 2,
    slug: 'brown-notebook-cover-paper-tube',
    title: 'Brown Notebook Cover Paper Tube',
    shortDescription:
      'Strong and durable paper tubes used inside notebook cover rolls, keeping the material neat, smooth and wrinkle-free during winding.',
    description:
      '<p>Strong and durable paper tubes used inside notebook cover rolls, keeping the material neat, smooth and wrinkle-free during winding.</p><p>These brown kraft paper tubes are manufactured to precise dimensions, ensuring consistent roll support and smooth unwinding in stationery manufacturing units. Custom lengths and diameters available on request.</p>',
    featuredImage: {
      id: 2,
      url: '/images/products/2 product.jpeg',
      alt: 'Brown Notebook Cover Paper Tube',
      width: 800,
      height: 600,
    },
    gallery: [],
    usedFor: ['Winding Notebook Cover Rolls'],
    applications: ['Stationery Industry', 'Notebook & Paper Manufacturing'],
    specifications: [
      { label: 'Thickness', value: '1.2 mm' },
      { label: 'Diameter', value: '18 mm – 25 mm' },
      { label: 'Length', value: '14 Inch' },
      { label: 'Size', value: '25 mm × 14 Inch' },
      { label: 'Weight', value: '20 Gram' },
      { label: 'Usage / Application', value: 'Winding Notebook Cover Rolls' },
    ],
    seoTitle: 'Brown Notebook Cover Paper Tube | FAB Paper Tube',
    seoDescription:
      'Durable brown notebook cover paper tubes. Thickness 1.2mm, Diameter 18–25mm, Length 14 Inch, Weight 20g. FAB Paper Tube, Gujarat.',
    acf: {},
    productOrder: 2,
    thickness: '1.2 mm',
    diameter: '18 mm – 25 mm',
    length: '14 Inch',
    size: '25 mm × 14 Inch',
    weight: '20 Gram',
    usage: 'Winding Notebook Cover Rolls',
  },
  {
    id: 3,
    slug: 'birthday-cake-sparkle-candle-tube',
    title: 'Birthday Cake Sparkle Candle Tube',
    shortDescription:
      'Precisely made paper tubes designed for birthday sparkle candles, offering good support during packaging and handling.',
    description:
      '<p>Precisely made paper tubes designed for birthday sparkle candles, offering good support during packaging and handling.</p><p>These tubes are engineered to exact dimensions required by candle manufacturers. The consistent wall thickness and smooth inner surface ensures proper fit and safe handling of sparkle candles in birthday cake applications.</p>',
    featuredImage: {
      id: 3,
      url: '/images/products/3 product.jpeg',
      alt: 'Birthday Cake Sparkle Candle Tube',
      width: 800,
      height: 600,
    },
    gallery: [],
    usedFor: ['Birthday Cake Sparkle Candles'],
    applications: ['Candle Manufacturing', 'Party & Celebration Products'],
    specifications: [
      { label: 'Thickness', value: '3 mm' },
      { label: 'Diameter', value: '8.5 mm' },
      { label: 'Length', value: '06 – 14 Inch' },
      { label: 'Size', value: 'As per Requirement' },
      { label: 'Weight', value: '30 Gram' },
      { label: 'Usage / Application', value: 'Birthday Cake Sparkle Candles' },
    ],
    seoTitle: 'Birthday Cake Sparkle Candle Tube | FAB Paper Tube',
    seoDescription:
      'Paper tubes for birthday cake sparkle candles. Thickness 3mm, Diameter 8.5mm, Length 6–14 Inch. Manufactured by FAB Paper Tube, Gujarat.',
    acf: {},
    productOrder: 3,
    thickness: '3 mm',
    diameter: '8.5 mm',
    length: '06 – 14 Inch',
    size: 'As per Requirement',
    weight: '30 Gram',
    usage: 'Birthday Cake Sparkle Candles',
  },
  {
    id: 4,
    slug: 'selfie-stick-pencil-crackers-tube',
    title: 'Selfie Stick Pencil Crackers',
    shortDescription:
      'Paper tubes designed for selfie stick firecrackers, providing strong support and reliable shape for the product.',
    description:
      '<p>Paper tubes designed for selfie stick firecrackers, providing strong support and reliable shape for the product.</p><p>Manufactured with precise wall thickness and consistent diameter to ensure the structural integrity required for firecracker applications. These tubes are produced under strict quality control to meet safety and performance requirements.</p>',
    featuredImage: {
      id: 4,
      url: '/images/products/4 product.jpeg',
      alt: 'Selfie Stick Pencil Crackers Tube',
      width: 800,
      height: 600,
    },
    gallery: [],
    usedFor: ['Selfie Stick Firecrackers'],
    applications: ['Firecracker Manufacturing', 'Cracker Industry'],
    specifications: [
      { label: 'Thickness', value: '2.5 mm' },
      { label: 'Diameter', value: '8.5 mm' },
      { label: 'Length', value: '14 Inch' },
      { label: 'Size', value: 'As per Requirement' },
      { label: 'Weight', value: '25 Gram' },
      { label: 'Usage / Application', value: 'Selfie Stick Firecrackers' },
    ],
    seoTitle: 'Selfie Stick Pencil Crackers Paper Tube | FAB Paper Tube',
    seoDescription:
      'Strong paper tubes for selfie stick pencil crackers. Thickness 2.5mm, Diameter 8.5mm, Length 14 Inch. FAB Paper Tube, Gujarat.',
    acf: {},
    productOrder: 4,
    thickness: '2.5 mm',
    diameter: '8.5 mm',
    length: '14 Inch',
    size: 'As per Requirement',
    weight: '25 Gram',
    usage: 'Selfie Stick Firecrackers',
  },
  {
    id: 5,
    slug: 'butterfly-firecracker-tube',
    title: 'Butterfly Firecracker Tube',
    shortDescription:
      'Small kraft paper tubes designed for butterfly firecrackers, providing reliable shape and support for the product.',
    description:
      '<p>Small kraft paper tubes designed for butterfly firecrackers, providing reliable shape and support for the product.</p><p>These compact tubes are manufactured with high precision to ensure consistent dimensions. The strong wall construction provides the shape retention and structural support required in butterfly firecracker manufacturing.</p>',
    featuredImage: {
      id: 5,
      url: '/images/products/5 product.jpeg',
      alt: 'Butterfly Firecracker Tube',
      width: 800,
      height: 600,
    },
    gallery: [],
    usedFor: ['Butterfly Firecrackers'],
    applications: ['Firecracker Manufacturing', 'Cracker Industry'],
    specifications: [
      { label: 'Thickness', value: '4 mm' },
      { label: 'Diameter', value: '8.5 mm' },
      { label: 'Length', value: '50 mm' },
      { label: 'Size', value: 'As per Requirement' },
      { label: 'Weight', value: '5 Gram' },
      { label: 'Usage / Application', value: 'Butterfly Firecrackers' },
    ],
    seoTitle: 'Butterfly Firecracker Tube | FAB Paper Tube',
    seoDescription:
      'Kraft paper tubes for butterfly firecrackers. Thickness 4mm, Diameter 8.5mm, Length 50mm, Weight 5g. FAB Paper Tube, Gujarat.',
    acf: {},
    productOrder: 5,
    thickness: '4 mm',
    diameter: '8.5 mm',
    length: '50 mm',
    size: 'As per Requirement',
    weight: '5 Gram',
    usage: 'Butterfly Firecrackers',
  },
  {
    id: 6,
    slug: 'thermal-roll-paper-tube',
    title: 'Thermal Roll Paper Tube',
    shortDescription:
      'High-quality paper cores designed for thermal paper rolls, providing consistent performance and reliable roll support.',
    description:
      '<p>High-quality paper cores designed for thermal paper rolls, providing consistent performance and reliable roll support.</p><p>These cores are precision manufactured to ensure perfect fit in thermal printers and POS machines. Consistent inner diameter and smooth surface ensures smooth paper feeding without jams or misalignment.</p>',
    featuredImage: {
      id: 6,
      url: '/images/products/6 product.jpeg',
      alt: 'Thermal Roll Paper Tube',
      width: 800,
      height: 600,
    },
    gallery: [],
    usedFor: ['Thermal Paper Rolls'],
    applications: ['Thermal Printing', 'POS & Billing Systems', 'Paper Converting'],
    specifications: [
      { label: 'Thickness', value: '3.2 mm' },
      { label: 'Diameter', value: '25 mm' },
      { label: 'Length', value: '44 Inch' },
      { label: 'Size', value: '25 mm × 44 Inch' },
      { label: 'Weight', value: '200 Gram' },
      { label: 'Usage / Application', value: 'Thermal Paper Rolls' },
    ],
    seoTitle: 'Thermal Roll Paper Tube | FAB Paper Tube',
    seoDescription:
      'Paper cores for thermal rolls. Thickness 3.2mm, Diameter 25mm, Length 44 Inch, Weight 200g. Manufactured by FAB Paper Tube, Gujarat.',
    acf: {},
    productOrder: 6,
    thickness: '3.2 mm',
    diameter: '25 mm',
    length: '44 Inch',
    size: '25 mm × 44 Inch',
    weight: '200 Gram',
    usage: 'Thermal Paper Rolls',
  },
  {
    id: 7,
    slug: 'mirchi-bomb-paper-tube',
    title: 'Mirchi Bomb Paper Tube',
    shortDescription:
      'Paper tubes specially made for Mirchi Bomb firecrackers, providing good strength, shape and reliable support.',
    description:
      '<p>Paper tubes specially made for Mirchi Bomb firecrackers, providing good strength, shape and reliable support.</p><p>These tubes are manufactured with consistent wall thickness and accurate dimensions to meet the exact requirements of Mirchi Bomb cracker manufacturing. The strong construction ensures product integrity throughout the manufacturing and packaging process.</p>',
    featuredImage: {
      id: 7,
      url: '/images/products/7 product.jpeg',
      alt: 'Mirchi Bomb Paper Tube',
      width: 800,
      height: 600,
    },
    gallery: [],
    usedFor: ['Mirchi Bomb Firecrackers'],
    applications: ['Firecracker Manufacturing', 'Cracker Industry'],
    specifications: [
      { label: 'Thickness', value: '1.5 mm' },
      { label: 'Diameter', value: '9 mm' },
      { label: 'Length', value: '64 mm' },
      { label: 'Size', value: 'As per Requirement' },
      { label: 'Weight', value: '2 Gram' },
      { label: 'Usage / Application', value: 'Mirchi Bomb Firecrackers' },
    ],
    seoTitle: 'Mirchi Bomb Paper Tube | FAB Paper Tube',
    seoDescription:
      'Paper tubes for Mirchi Bomb firecrackers. Thickness 1.5mm, Diameter 9mm, Length 64mm, Weight 2g. FAB Paper Tube, Gujarat.',
    acf: {},
    productOrder: 7,
    thickness: '1.5 mm',
    diameter: '9 mm',
    length: '64 mm',
    size: 'As per Requirement',
    weight: '2 Gram',
    usage: 'Mirchi Bomb Firecrackers',
  },
  {
    id: 8,
    slug: 'stretch-film-roll-paper-tube',
    title: 'Stretch Film Roll Paper Tube',
    shortDescription:
      'Quality paper cores made for stretch film rolls, ensuring firm support and neat, uniform winding.',
    description:
      '<p>Quality paper cores made for stretch film rolls, ensuring firm support and neat, uniform winding.</p><p>These heavy-duty paper cores are built to withstand the tension of stretch film winding operations. The precise inner diameter and strong wall construction ensures reliable performance in industrial stretch film manufacturing and packaging lines.</p>',
    featuredImage: {
      id: 8,
      url: '/images/products/8 product.jpeg',
      alt: 'Stretch Film Roll Paper Tube',
      width: 800,
      height: 600,
    },
    gallery: [],
    usedFor: ['Stretch Film Rolls'],
    applications: ['Packaging Industry', 'Industrial Film Winding', 'Stretch Film Manufacturing'],
    specifications: [
      { label: 'Thickness', value: '4 mm' },
      { label: 'Diameter', value: '25 mm' },
      { label: 'Length', value: '12 Inch' },
      { label: 'Size', value: '25 mm × 12 Inch' },
      { label: 'Weight', value: '80 Gram' },
      { label: 'Usage / Application', value: 'Stretch Film Rolls' },
    ],
    seoTitle: 'Stretch Film Roll Paper Tube | FAB Paper Tube',
    seoDescription:
      'Paper cores for stretch film rolls. Thickness 4mm, Diameter 25mm, Length 12 Inch, Weight 80g. FAB Paper Tube, Gujarat.',
    acf: {},
    productOrder: 8,
    thickness: '4 mm',
    diameter: '25 mm',
    length: '12 Inch',
    size: '25 mm × 12 Inch',
    weight: '80 Gram',
    usage: 'Stretch Film Rolls',
  },
];
